AllCops:
  TargetRubyVersion: 2.3

Layout/EmptyLinesAroundBlockBody:
  Enabled: false

Layout/EmptyLinesAroundClassBody:
  Enabled: false

Layout/EmptyLinesAroundModuleBody:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Metrics/ClassLength:
  Exclude:
    - 'test/**/*'

Metrics/LineLength:
  Enabled: false

Style/Documentation:
  Enabled: false
