AllCops:
  TargetRubyVersion: 2.3

Layout/EmptyLinesAroundClassBody:
  Enabled: false

Layout/EmptyLinesAroundBlockBody:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Metrics/LineLength:
  Enabled: false

Style/Documentation:
  Enabled: false
