#!/usr/bin/env ruby
# frozen_string_literal: true

lib_path = File.expand_path('../lib', __dir__)
$LOAD_PATH.unshift(lib_path) unless $LOAD_PATH.include?(lib_path)

require 'climbcomp'
require 'climbcomp/cli'
# Note: This sets the global config for the CLI (should only ever be required here)
require 'climbcomp/cli/initializer'

Signal.trap('INT') do
  warn("\n#{caller.join("\n")}: interrupted")
  exit(1)
end

begin
  Climbcomp::CLI.start
rescue Climbcomp::CLI::Error => err
  puts "ERROR: #{err.message}"
  exit 1
end
