#!/usr/bin/env ruby
# frozen_string_literal: true

lib_path = File.expand_path('../lib', __dir__)
$LOAD_PATH.unshift(lib_path) unless $LOAD_PATH.include?(lib_path)

require 'climbcomp'
require 'climbcomp/cli'

token_store = Climbcomp::OAuth2::TokenStore.new(Climbcomp.config.token_store_path)
Climbcomp.configure do |c|
  c.oidc_audience = 'https://staging.climbcomp.com/'
  c.token = token_store.retrieve
end

Signal.trap('INT') do
  warn("\n#{caller.join("\n")}: interrupted")
  exit(1)
end

begin
  Climbcomp::CLI.start
rescue Climbcomp::CLI::Error => err
  puts "ERROR: #{err.message}"
  exit 1
end

# Ensure token is always stored (could have been refreshed in `FaradayMiddleware`).
token_store.store(Climbcomp.config.token)
